export enum PoolName {
    fridayEvening = 'fridayEvening',
    saturdayMorning = 'saturdayMorning',
    saturdayEvening = 'saturdayEvening',
    sundayMorning = 'sundayMorning',
}

export enum RoomName {
    'NotSet' = 'NotSet',
    'Styrerom1' = 'Styrerom1',
    'Styrerom2' = 'Styrerom2',
    'Styrerom3' = 'Styrerom3',
    'Styrerom4' = 'Styrerom4',
    'Styrerom5' = 'Styrerom5',
    'Styrerom6' = 'Styrerom6',
    'Klang' = 'Klang',
    'Sonate' = 'Sonate',
    'Ballade' = 'Ballade',
    'Klaver' = 'Klaver',
    'Hymne' = 'Hymne',
    'Fanfare' = 'Fanfare',
    'Kammer' = 'Kammer',
    'Beyer' = 'Beyer',
    'Siljuslåtten' = 'Siljuslåtten',
    'PeerGynt' = 'Peer Gynt',
    'AnitrasDans' = 'Anitras Dans',
    'SolveigsSang' = 'Solveigs Sang',
    'Werenskiold' = 'Werenskiold',
    'Welhaven' = 'Welhaven',
}
