version: "2"
run:
  concurrency: 8
  modules-download-mode: readonly
  issues-exit-code: 2
  tests: false
  allow-parallel-runners: true
  skip-files:
    - ".*_templ\\.go"
formatters:
  exclusions:
    generated: lax
linters:
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
