// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Menu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.main-menu-link {\n\t\t\tdisplay: flex;\n\t\t\talign-items: center;\n\t\t\tcolor: var(--color-secondary);\n\t\t\ttext-decoration: none;\n\t\t\ttext-transform: uppercase;\n\t\t\tmargin-left: 1rem;\n\t\t\tpadding: 0.5rem;\n\t\t}\n\t\t.main-menu-link:hover {\n\t\t\tbackground-color: rgba(255, 255, 255, 0.1);\n\t\t}\n\t</style><nav style=\"\n\t\tdisplay:flex;\n\t\talign-items: center;\n\t\tBackground-color: #2d3748;\n\t\twidth: 100%;\n\t\tpadding: 0.25rem;\n\t\tmargin-bottom: 1rem;\"><a href=\"/\"><img src=\"/static/assets/RegnconLogo.svg\" alt=\"logo\" style=\"width: 2rem; height: 2rem;\"></a> <a href=\"/\" class=\"main-menu-link\"><img src=\"/static/assets/icons/house-solid.svg\" alt=\"hjem\" style=\"width: 1.25rem; height: 1.25rem;\tmargin-right: 0.25rem;\"> Hjem</a></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
