services:
    backup-service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backup-dev
        ports:
            - 7331:7331
            - 8080:8080
        volumes:
            - .:/data
        env_file:
            - .env
        restart: unless-stopped
