name: Conoginizer build test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Runs on any open or reopened pull request
  pull_request:
    branches: ["main"]
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Caching is enabled by default
        # https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go#caching-dependencies
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '1.24'


      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate template files
        run: templ generate

      - name: Install dependencies
        run: go get .

      - name: Generate binary
        run: go build -v ./...

      - name: Test binary
        run: go test

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: TestResults.json
