# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy Backup-service
on:
    push:
        branches:
            - main
        paths:
            - "backup-service/**"
jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        environment: production
        concurrency: deploy-group # optional: ensure only one action runs at a time
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl -c backup-service/fly.toml deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_BACKUP_API_TOKEN }}
